### ISSUE TITLE
A11Y Images with lots of content are not really accessible

### ISSUE THREAD

**Issue by TomCools** [EdwinVW/dapr-workshop#15]
Noticed this issue while reviewing @mthmulders Java merge request, but goes for the .NET side as well.

The workshop contains quite a few images which contain code/logs which can't be read by screenreaders.
The general moto in the A11Y world seems to be "Code blocks, not screenshots". This would also make it easier to version (in case some of the examples ever change, we don't need to create new screenshots.

Very open to discuss this further and contribute.

**Comment by mthmulders** [comment]
For code blocks and snippets of logs, I agree that having them as text would be better than having them as images.

There's also a few diagrams in the repository. What would the general advice be with regards to those?

**Comment by TomCools** [comment]
For diagrams: https://www.w3.org/WAI/tutorials/images/complex/

**Comment by EdwinVW** [comment]
For .NET, all code snippets are text (totally agree these should be text-based).
The log output screenshots are images and they can be changed pretty fast imho.
The diagram images come from a slide-deck and can also be changed with little effort.

**Comment by wmeints** [comment]
I can do this for the Python version immediately so they're done when my PR gets merged.

**Comment by EdwinVW** [comment]
For the .NET version I'm fine with the current situation.

@mthmulders Does the Java version of the workshop needs work to fix this issue? If not, I'd suggest to close this issue.

**Comment by mthmulders** [comment]
@EdwinVW the Java track is on par with the .NET track as far as A11Y is concerned.

I would say it makes sense to make the workshop as accessible as reasonably possible. I think converting log screenshots into text blocks shouldn't be too much work. The diagrams may prove to be a bit more work, as that typically includes alignment of blocks & arrows. Plus it would be more work to keep them up-to-date with the slide deck.

But I would prefer for the whole workshop to be uniform in this regard. It would be a bit odd to have screenshots of logging in one track, and text-based screenshots in another track. The diagrams are shared across tracks so that would be one thing to fix for all tracks at once.

May I suggest that we at least convert all logging screenshot into text blocks? I think the diagrams are supplementary to the text. But if you follow either of the tracks and you cannot read the log screenshots, how are you going to verify that you did it correctly?

**Comment by EdwinVW** [comment]
Makes sense. I'll convert te logging screenshots in the .NET part to text.

But I would really like to keep the diagrams as is because we use those everywhere (in the Dapr book, sample app, slides for talks and the workshop).

**Comment by EdwinVW** [comment]
Closed too soon. Close when Java screenshots have been replaced.
